name: CDXGen

on: workflow_dispatch

jobs:
  # Build job
  build:
    # Specify runner +  build & upload the static files as an artifact
    runs-on: ubuntu-latest
    steps:
      - name: "Checout code"
        uses: actions/checkout@v4
  
      - name: "Check input"
        shell: bash
        run: |
          if [[ "${{ inputs.project_type }}" != "" ]]
          then
            echo "Project type is provided: ${{ inputs.project_type }}"
            echo "PROJECT_TYPE=-t ${{ inputs.project_type }}" >> $GITHUB_ENV
          else
            echo "Project type is not provided"
            echo "PROJECT_TYPE=" >> $GITHUB_ENV
          fi
  
      - name: "Generate BOM"
        run: |
          cd ${GITHUB_WORKSPACE}
          docker run --rm -v /tmp:/tmp -v $(pwd):/app:rw -t ghcr.io/cyclonedx/cdxgen:v8.6.0 -r /app -p -o /app/${{ github.event.repository.name }}_sbom.json "${{ env.PROJECT_TYPE }}"
          docker rmi -f $(docker images -aq)
        shell: bash
  
      - name: "Upload SBOM file"
        uses: actions/upload-artifact@v4.6.0
        with:
          name: "BOM file"
          path: ${{ github.workspace }}/**/${{ github.event.repository.name }}_sbom.json
          retention-days: 5
  
      - name: "Generate Depscan report"
        run: |
          cd ${GITHUB_WORKSPACE}
          docker run --rm -v $PWD:/app ghcr.io/owasp-dep-scan/dep-scan \
          --src /app --reports-dir /app/reports --bom /app/${{ github.event.repository.name }}_sbom.json
        shell: bash
  
      - name: "Upload Depscan report"
        uses: actions/upload-artifact@v4.6.0
        with:
          name: "DEPSCAN report"
          path: ${{ github.workspace }}/**/reports/*
          retention-days: 5

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: ${{ github.workspace }}/**/reports/*

  # Deployment job
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
      - name: "Summary"
        run: |
          echo "${{ steps.deployment.outputs.page_url }}" >> $GITHUB_STEP_SUMMARY
